### ISSUE TITLE
OSX stuck on installation 

### ISSUE THREAD

**Issue by dkun7944** [extemporelang/extemporelang.github.io#10]
Trying to install Extempore on OSX 10.13.3. I downloaded the pre-built binary and ran extempore from within the folder after copying it to my Applications folder. The installation is stuck. It's been in this state for almost an hour and nothing has happened.

Am I doing something wrong?

<img width="729" alt="screen shot 2018-03-03 at 8 24 36 pm" src="https://user-images.githubusercontent.com/2880086/36941089-15400b48-1f21-11e8-9aea-27e9b09af045.png">

**Comment by digego** [comment]
Hi Daniel,

Actually, looks like you're doing everything right :)
Extempore is installed and running, it's just sitting there waiting for you
to do something :)
Try connecting to 7098 from vscode and send (println "hello world")

Cheers,
Andrew.

**Comment by dkun7944** [comment]
@digego Thanks so much, that worked! I really appreciate you bearing with me - I'm new to live coding in music.
