### ISSUE TITLE
Livecoding chat is moving from slack to rocket chat

### ISSUE THREAD

**Issue by cianoc** [extemporelang/extemporelang.github.io#11]
Alex Mclean has very kindly decided to host it at toplap and the extempore channel has been ported (with full history!). Obviously the slack channel isn't going anywhere, but I think the momentum is going to move to the new location because in most regards it seems like a better thing.

My feeling is that Extempore should move to the new chat server, in which case once the trial has ended we should change all links on the website to point to the new location.

**Comment by benswift** [comment]
Sure, I'm ok with this - if that's where the community's going anway. @digego , what do you think? Which link should we have on the Extempore homepage?

**Comment by digego** [comment]
No objections from me, whatever you guys think is best.

**Comment by benswift** [comment]
yep, done - will have a look and update all references shortly
