### ISSUE TITLE
Propose to change site design

### ISSUE THREAD

**Issue by cyblue9** [extemporelang/extemporelang.github.io#21]
Hi @benswift !

I'm working on https://github.com/extemporelang/extemporelang.github.io/issues/6 now.

I thought while working on , how about changing the design of the site?

The current design is wasting the left side of the site.
So, It is good to move position of chapter index from left to top.

<img width="1280" alt="2018-12-23 20 56 07" src="https://user-images.githubusercontent.com/16382693/50383417-779cd880-06f6-11e9-9935-071151ce783e.png">

What do you think?

**Comment by benswift** [comment]
yeah, that sounds fine - good even.

To be honest, the layout of the site was quickly hacked-together, and there are lots of things which could be better. So, I think in general you should feel free to make minor changes like this---you don't need to ask permissions for every little thing. Feel free to just make the changes, if I really don't like them I'll just revert 😛 

Thanks for all your work with this---it's a really valuable service to the Extempore community.

**Comment by cyblue9** [comment]
Hi @benswift 

Merry Christmas! 🎄

> To be honest, the layout of the site was quickly hacked-together, and there are lots of things which could be better. 

If you have some ideas of layout of the site, please could you create issues of these?

> So, I think in general you should feel free to make minor changes like this---you don't need to ask permissions for every little thing. Feel free to just make the changes, if I really don't like them I'll just revert 😛

Thank you, I will do freely!
To make it easier to review, I will try to make the granularity of commit as small as possible.

> Thanks for all your work with this---it's a really valuable service to the Extempore community.

No problem! Let the community grow more!! 😄

**Comment by benswift** [comment]
> If you have some ideas of layout of the site, please could you create issues of these?

Ok, sure. None right this minute, but I'll file issues as they arise.
