### ISSUE TITLE
Inconsistency between docs

### ISSUE THREAD

**Issue by bradrn** [extemporelang/extemporelang.github.io#24]
This example in the new docs (https://extemporelang.github.io/docs/overview/time/) doesn't seem to work:

```lisp
;; load the instruments file
(sys:load "libs/core/instruments.xtm")

;; define a synth using the predefined instrument fmsynth
(make-instrument synth fmsynth)

;; add the instrument to the DSP output callback
(bind-func dsp:DSP
  (lambda (in time chan dat)
    (synth in time chan dat)))
(dsp:set! dsp)

;; schedule three nodes to play in succession
(define play-seq
  (lambda ()
    (play-note (now) synth 60 80 10000)
    (play-note (+ (now) 22050) synth 64 80 10000)
    (play-note (+ (now) 44100) synth 67 80 10000)))

;; play
(play-seq)
```

In particular, `(make-instrument synth fmsynth)` gives an error saying that `make-instrument` doesn't exist. However, the corresponding example in the old docs (http://digego.github.io/extempore/time.html) does work:

```lisp
;; load the instruments file
(sys:load "libs/core/instruments.xtm")

;; define a synth using the provided components
;; synth_note_c and synth_fx
(bind-instrument synth synth_note_c synth_fx)

;; add the instrument to the DSP output callback
(bind-func dsp:DSP
  (lambda (in time chan dat)
    (synth in time chan dat)))
(dsp:set! dsp)

;; schedule three nodes to play in succession
(define play-seq
  (lambda ()
    (play-note (now) synth 60 80 10000)
    (play-note (+ (now) 22050) synth 64 80 10000)
    (play-note (+ (now) 44100) synth 67 80 10000)))

;; play
(play-seq)
```

Why is it that the old, outdated docs work whereas the new docs don't?

**Comment by cyblue9** [comment]
Hi @bradrn !

Please read https://github.com/digego/extempore/issues/297 and https://github.com/digego/extempore/issues/347.

If you use binary version, you don't use `make-instrument` macro.

**Comment by bradrn** [comment]
Thanks @cyblue9!

I'm still wondering though: shouldn't the docs describe the latest released version, as opposed to describing HEAD?

**Comment by cyblue9** [comment]
Uh...

@benswift @digego 
what do you think?

**Comment by digego** [comment]
A new release is coming, albeit slowly, and so it makes sense, given our limited resources, to move the docs towards that next release.

Sorry for any confusion.

Cheers
Andrew

On 6 April 2019 4:19:00 pm AEST, blue9 <notifications@github.com> wrote:
>Uh...
>
>@benswift @digego 
>what do you think?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/extemporelang/extemporelang.github.io/issues/24#issuecomment-480478187

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bradrn** [comment]
Thanks @digego! That makes sense. I'm looking forward to the next release!

**Comment by benswift** [comment]
Yep. Thanks for your patience.
