### ISSUE TITLE
The nature of the 'r' in 'cosr' etc.

### ISSUE THREAD

**Issue by soulofmischief** [extemporelang/extemporelang.github.io#34]
The pattern language guide says the reason for the trailing 'r' is lost to time.

Doesn't it just stand for 'range'? cosine range, sin range, etc.?

**Comment by digego** [comment]
Maybe, I can't remember why I used the r when I wrote it.  It *might* have
been range - can't remember ;)

**Comment by soulofmischief** [comment]
The innerworkings of your mind are truly an enigma, Andrew!

I'll go ahead and close thread then. :p
