### ISSUE TITLE
Blog link to team 404s

### ISSUE THREAD

**Issue by Chovin** [extemporelang/extemporelang.github.io#4]
[link](https://github.com/orgs/extemporelang/teams/docs) on [blog post](https://extemporelang.github.io/blog/2017/11/29/extempore-docs-update/) 404s
[on line 41](https://github.com/extemporelang/extemporelang.github.io/blame/master/_posts/2017-11-29-extempore-docs-update.md#L14) for convenience

I'm assuming it's only viewable for team members

**Comment by benswift** [comment]
Yep, thanks for the heads up.
