### ISSUE TITLE
Problems with Quickstart guide.

### ISSUE THREAD

**Issue by michaelmariaott** [extemporelang/extemporelang.github.io#42]
The following part of the quickstart guide works without issues:
```
(println "Hello, World!")

(bind-func sine:DSP
  (lambda (in time chan dat)
    (* .1 (cos (* (convert time) 0.4)))))

;; re-bind sine to 0 to stop output
(bind-func sine:DSP
  (lambda (in time chan dat)
    0.0))
;; use sine as dsp sink
(dsp:set! sine)
```

Afterwards I run into problems. After evaluating:
```
(sys:load "examples/sharedsystem/setup.xtm")

(:> ascending-scale 4 0 (play syn1 @1 80 dur) (scale 4 8))
```
...the console prints, that it's starting the pattern, but there is no sound.

I tried restarting extempore and immediately evaluating `(sys:load "examples/sharedsystem/setup.xtm")
`, but then I get:
```
Audio underflow: are you pushing extempore too hard?
```
after it loads the sharedsystem. If I ignore the audio underflow and evaluate `(:> ascending-scale 4 0 (play syn1 @1 80 dur) (scale 4 8))`, I get sound, but in horrible quality and with horrible timing (because of the audio underflow).

I'm on Windows 11, using VSCode with the extempore extension as an editor.

**Comment by cyblue9** [comment]
@michaelmariaott 

> ...the console prints, that it's starting the pattern, but there is no sound.

It's a matter of course.
Because, DSP is bound with sine by `(dsp:set! sine)`.
If you wish to get sound, you must bind DSP and syn1.

> Audio underflow: are you pushing extempore too hard?

Your PC specs may not be enough...
Or try closing other apps.

**Comment by michaelmariaott** [comment]
@cyblue9 

I did try to bind dsp to syn1 by evaluating `(dsp:set! syn1)`. This throws the following exception:
```
Error: evaluating expr: (dsp:set! syn1) n:0] 4:[ 0% n:0] 5:[ 0% n/a]                                            
stack-catch: ()
stack-catch: map
stack-catch: ()
stack-catch: ()
stack-catch: ()
stack-catch: ()
Attempting to return a string from non-symbol obj #<CPTR: 000002595B142AA0>
```

Regarding the audio underflow: I doubt it has to do with my pc specs. I did not have any other windows open. My laptop can run other audio programming environements without any problem (Max, Pd, CSound, Supercollider, ...).
Also the audio underflow occurs, when I evaluate  `(sys:load "examples/sharedsystem/setup.xtm")` in a fresh extempore process. At this point, extempore is using 3.4% of my cpu and 936MB Ram and my overall cpu usage is at 18% and Ram at 25% (i7-8650U CPU @ 1.90GHz   2.11 GHz, 32GB Ram).

**Comment by cyblue9** [comment]
@michaelmariaott 

> I did try to bind dsp to syn1 by evaluating (dsp:set! syn1). This throws the following exception:

You evaluate `(sys:load "examples/sharedsystem/audiosetup.xtm")`. 
Because, syn1 is evaluated in below. (You don't evaluate of syn1 yourself.)
https://github.com/digego/extempore/blob/a3a2563697496c0355c18e4edc92b0c85fe06578/examples/sharedsystem/audiosetup.xtm#L50

> Regarding the audio underflow: I doubt it has to do with my pc specs.

Uh..., maybe `setup.xtm` is problem.
so, you try to do below step.

step1: You evaluate `(sys:load "examples/sharedsystem/audiosetup.xtm")`. 
step2: You evaluate `(sys:load "examples/sharedsystem/pattern_basics.xtm")`. 

Do you listen to good sound??

**Comment by benswift** [comment]
hey @michaelmariaott the sharedsystem re-evaluates and sets up its own `dsp` closure & signal chain, so it's designed to be run from a fresh restart[^restart].

The audio underflow issue is best solved by bumping up the frame size when you start extempore, with e.g.

    $ extempore --frames 4096

As always there's a tradeoff between latency and throughput, so try and find a frame size which works for your system.

I'll try and make it clearer in the startup docs.

[^restart]: in principle it could be changed to be more flexible to be re-run over the top of things, but given that it's hard to know what's been evaluated before we just do it this way for now

**Comment by cyblue9** [comment]
@benswift 
Thank you for comment！
