### ISSUE TITLE
search box doesn't do anything

### ISSUE THREAD

**Issue by benswift** [extemporelang/extemporelang.github.io#6]
the html for the (top-right) search field is in `_includes/topnav.html`, and should probably just do a google search with site:extemporelang.github.io but at the moment it does nothing.

**Comment by cyblue9** [comment]
Hi @benswift!

I am interested in improvement of this problem!

Two libraries are conceivable for the inside search.
Two libraries is  and [lunr.js](https://lunrjs.com/) and [algolia](https://community.algolia.com/docsearch/).

- lunr.js
  - advantage
    - Searching by client side
  - disadvantage
- algolia
  - advantage
    - [Can instant search](https://www.algolia.com/doc/assets/images/guides/search-ui/instant-search-1-32a7da2f.gif)
  - disadvantage
    - Need to register
    - [May cost](https://www.algolia.com/pricing)(It might be fine even for a free plan. How many PVs per month in extempore.io?)

I think ```algolia``` is better. Because, instant search is nice function and Using`algolia` is probably easy. If there is no problem with the free plan.

What do you think?

**Comment by benswift** [comment]
Hmm, good ideas there. I guess the other option is that we just have it point to a straight search on Google (with `site:extemporelang.github.io` added). However, it's **very** unlikely that we'd hit the Algolia limits on the free plan. So perhaps let's go with that option :)

I'm sorry that I haven't approved the other PR yet either, but will have some time to look at it later this week.

**Comment by cyblue9** [comment]
Thank to replay😁

>  I guess the other option is that we just have it point to a straight search on Google (with site:extemporelang.github.io added). 

It's good. This option is easy to implement. But, As a disadvantage
- The 'google' logo mark is displayed
- A advertisement is displayed in search result page

It might be not good as UI.

> However, it's very unlikely that we'd hit the Algolia limits on the free plan. So perhaps let's go with that option :)

Oh, it is possible on the free plan!
I found [Algolia for Jekyll](https://community.algolia.com/jekyll-algolia/). Implementation may be easy with this.
If we use Alogolia, need to create [Algolia account](https://www.algolia.com/users/sign_up/hacker).
Which is better to create Algolia account, by extempore account or my account?
(If possible, Please to create Algolia account by extempore github account and to teach me API key by some means.)  

> I'm sorry that I haven't approved the other PR yet either, but will have some time to look at it later this week.

No problem😃

**Comment by cyblue9** [comment]
Ping... @benswift

**Comment by cyblue9** [comment]
> Ok, I've signed up for algolia. What's the best (encrypted) way to send the credentials to you? Do you have signal/whatsapp?

Sorry, I don't have signal or whatsapp. (They are not used much in Japan)
Do you have another idea?
If you don't have another idea, I will install whatsapp.

> Also, you should have access to the main docs website repo: I added you to the docs sub-team under the Extempore organisation on GH.

Thanks!

**Comment by benswift** [comment]
Well, we could do some pgp shenanigans. Or you could just get Whatsapp - what's your preference?

**Comment by cyblue9** [comment]
Thank you for suggesting another idea!
I knew GPG for the first time. It looks good.
If you agree GPG, I will create my public key and private key, tell you my public key.

**Comment by benswift** [comment]
Yep, sounds good.

**Comment by cyblue9** [comment]
I sent mail to you.
Please replay 😄

**Comment by benswift** [comment]
added in #22
