### ISSUE TITLE
add VSCode docs to editor support page

### ISSUE THREAD

**Issue by benswift** [extemporelang/extemporelang.github.io#8]
The VSCode suppport is pretty basic, but is probably as good as Atom (and will hopefully soon be *better* than Atom. So we should add those instructions to the editor support page.

Soon, we should change the "getting started" stuff to suggest VSCode rather than Atom for those who don't have rusted-on editor hangups.

**Comment by hellerve** [comment]
It’s in now, right? Can this be closed then?

**Comment by benswift** [comment]
Yeah, it's done.
